import { Link } from "react-router-dom";
import { SEO } from "@/components/SEO";
import { ArrowLeft } from "lucide-react";
import { Button } from "@/components/ui/button";

const Disclaimer = () => (
  <div className="min-h-screen bg-background">
    <SEO
      title="Legal Disclaimer | Tandon Associates"
      description="Important disclaimers about AI-generated legal research, drafts, and analyses on the Tandon Associates platform."
      path="/disclaimer"
    />
    <header className="border-b border-border py-4">
      <div className="container mx-auto px-4 flex items-center gap-3">
        <Button variant="ghost" size="icon" asChild>
          <Link to="/"><ArrowLeft className="w-4 h-4" /></Link>
        </Button>
        <span className="font-serif text-xl font-bold">Tandon <span className="text-gradient-gold">Associates</span></span>
      </div>
    </header>
    <main className="container mx-auto px-4 py-12 max-w-3xl prose prose-sm dark:prose-invert">
      <h1 className="font-serif">Legal Disclaimer</h1>
      <p className="text-muted-foreground">Last updated: March 2026</p>

      <h2>AI-Generated Content</h2>
      <p>The legal research results, case analyses, and document drafts generated by Tandon Associates' AI tools are provided for informational and reference purposes only. They do not constitute legal advice and should not be relied upon as such.</p>

      <h2>Professional Review Required</h2>
      <p>All AI-generated content should be reviewed and verified by a qualified legal professional before use in any legal proceeding, filing, or client communication. The AI may produce inaccurate, incomplete, or outdated information.</p>

      <h2>No Attorney-Client Relationship</h2>
      <p>Use of this platform does not create an attorney-client relationship between you and Tandon Associates. The platform is a technology tool designed to assist legal professionals in their practice.</p>

      <h2>Accuracy</h2>
      <p>While we strive for accuracy, we cannot guarantee that case citations, statutory references, or legal analyses are complete or current. Laws and regulations change frequently, and AI models may not reflect the most recent developments.</p>

      <h2>Jurisdiction</h2>
      <p>The platform is primarily designed for Indian legal practice. Content may not be applicable to other jurisdictions. Users should verify jurisdiction-specific requirements independently.</p>
    </main>
  </div>
);

export default Disclaimer;
