// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.3";

// src/lib/mcp/tools/list-cases.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.3";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.95.3";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("Supabase publishable key is not configured");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function unauthenticated() {
  return {
    content: [{ type: "text", text: "Not authenticated." }],
    isError: true
  };
}

// src/lib/mcp/tools/list-cases.ts
var list_cases_default = defineTool({
  name: "list_cases",
  title: "List cases",
  description: "List the signed-in user's legal cases, optionally filtered by status or a text search on the title.",
  inputSchema: {
    search: z.string().trim().max(200).optional().describe("Optional text to match against case titles."),
    status: z.string().trim().max(50).optional().describe("Optional case status filter (e.g. active, closed)."),
    limit: z.number().int().min(1).max(100).default(20).describe("Maximum number of cases to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("cases").select("id,title,case_number,cnr_number,court,judge,status,practice_area,next_hearing_date,created_at").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (search) query = query.ilike("title", `%${search}%`);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { cases: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-case.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.3";
import { z as z2 } from "npm:zod@^3.25.76";
var get_case_default = defineTool2({
  name: "get_case",
  title: "Get case detail",
  description: "Fetch one case owned by the signed-in user, with its client, hearings and open tasks.",
  inputSchema: { case_id: z2.string().uuid().describe("The case id.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ case_id }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const supabase = supabaseForUser(ctx);
    const [caseRes, hearingsRes, tasksRes] = await Promise.all([
      supabase.from("cases").select("*, clients(id,name,email,phone)").eq("id", case_id).maybeSingle(),
      supabase.from("hearings").select("id,date,court,judge,purpose,outcome,source").eq("case_id", case_id).order("date", { ascending: true }),
      supabase.from("tasks").select("id,title,due_date,completed").eq("case_id", case_id).order("due_date", { ascending: true })
    ]);
    const error = caseRes.error ?? hearingsRes.error ?? tasksRes.error;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!caseRes.data) return { content: [{ type: "text", text: "Case not found." }], isError: true };
    const payload = { case: caseRes.data, hearings: hearingsRes.data ?? [], tasks: tasksRes.data ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-clients.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.3";
import { z as z3 } from "npm:zod@^3.25.76";
var list_clients_default = defineTool3({
  name: "list_clients",
  title: "List clients",
  description: "List the signed-in user's clients, optionally filtered by a name search.",
  inputSchema: {
    search: z3.string().trim().max(200).optional().describe("Optional text to match against client names."),
    limit: z3.number().int().min(1).max(100).default(20).describe("Maximum number of clients to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("clients").select("id,name,email,phone,address,notes,created_at").order("name", { ascending: true }).limit(limit ?? 20);
    if (search) query = query.ilike("name", `%${search}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { clients: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-upcoming-hearings.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.3";
import { z as z4 } from "npm:zod@^3.25.76";
var list_upcoming_hearings_default = defineTool4({
  name: "list_upcoming_hearings",
  title: "List upcoming hearings",
  description: "List the signed-in user's hearings scheduled from today onwards, with case titles.",
  inputSchema: {
    days: z4.number().int().min(1).max(365).default(30).describe("How many days ahead to look."),
    limit: z4.number().int().min(1).max(100).default(25).describe("Maximum number of hearings to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ days, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const supabase = supabaseForUser(ctx);
    const today = /* @__PURE__ */ new Date();
    const until = new Date(today.getTime() + (days ?? 30) * 864e5);
    const { data, error } = await supabase.from("hearings").select("id,date,court,judge,purpose,outcome,source,cases(id,title,case_number)").gte("date", today.toISOString().slice(0, 10)).lte("date", until.toISOString().slice(0, 10)).order("date", { ascending: true }).limit(limit ?? 25);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { hearings: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-task.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.3";
import { z as z5 } from "npm:zod@^3.25.76";
var create_task_default = defineTool5({
  name: "create_task",
  title: "Create case task",
  description: "Create a task on one of the signed-in user's cases.",
  inputSchema: {
    case_id: z5.string().uuid().describe("The case the task belongs to."),
    title: z5.string().trim().min(1).max(300).describe("Short task title."),
    description: z5.string().trim().max(4e3).optional().describe("Optional task detail."),
    due_date: z5.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe("Optional due date as YYYY-MM-DD.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ case_id, title, description, due_date }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("tasks").insert({ case_id, title, description: description ?? null, due_date: due_date ?? null, user_id: ctx.getUserId() }).select("id,title,due_date,completed,case_id").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { task: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "flfxjovxeeewldeunetc";
var mcp_default = defineMcp({
  name: "legal-genie-ai",
  title: "Legal Genie AI",
  version: "0.1.0",
  instructions: "Tools for Legal Genie AI, an Indian legal practice platform. Use `list_cases` and `get_case` to inspect the signed-in user's matters, `list_clients` for their client roster, `list_upcoming_hearings` for their court calendar, and `create_task` to add follow-up work to a case. All data is scoped to the authenticated user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_cases_default, get_case_default, list_clients_default, list_upcoming_hearings_default, create_task_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.3/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
