ALTER POLICY "Users can view own profile" ON public.profiles TO authenticated;
ALTER POLICY "Users can insert own profile" ON public.profiles TO authenticated;
ALTER POLICY "Users can view own roles" ON public.user_roles TO authenticated;
ALTER POLICY "Users can view own search history" ON public.search_history TO authenticated;
ALTER POLICY "Users can insert own search history" ON public.search_history TO authenticated;
ALTER POLICY "Users can delete own search history" ON public.search_history TO authenticated;
ALTER POLICY "Admins can view all search history" ON public.search_history TO authenticated;
ALTER POLICY "Users can view own clients" ON public.clients TO authenticated;
ALTER POLICY "Users can insert own clients" ON public.clients TO authenticated;
ALTER POLICY "Users can update own clients" ON public.clients TO authenticated;
ALTER POLICY "Users can delete own clients" ON public.clients TO authenticated;
ALTER POLICY "Admins can view all clients" ON public.clients TO authenticated;
ALTER POLICY "Users can view own cases" ON public.cases TO authenticated;
ALTER POLICY "Users can insert own cases" ON public.cases TO authenticated;
ALTER POLICY "Users can delete own cases" ON public.cases TO authenticated;
ALTER POLICY "Admins can view all cases" ON public.cases TO authenticated;
ALTER POLICY "Users can view own hearings" ON public.hearings TO authenticated;
ALTER POLICY "Users can insert own hearings" ON public.hearings TO authenticated;
ALTER POLICY "Users can delete own hearings" ON public.hearings TO authenticated;
ALTER POLICY "Users can view own tasks" ON public.tasks TO authenticated;
ALTER POLICY "Users can insert own tasks" ON public.tasks TO authenticated;
ALTER POLICY "Users can delete own tasks" ON public.tasks TO authenticated;
ALTER POLICY "Users can view own case notes" ON public.case_notes TO authenticated;
ALTER POLICY "Users can insert own case notes" ON public.case_notes TO authenticated;
ALTER POLICY "Users can delete own case notes" ON public.case_notes TO authenticated;
ALTER POLICY "Users can view own layout" ON public.user_dashboard_layouts TO authenticated;
ALTER POLICY "Users can insert own layout" ON public.user_dashboard_layouts TO authenticated;
ALTER POLICY "Users can view own preferences" ON public.user_preferences TO authenticated;
ALTER POLICY "Users can insert own preferences" ON public.user_preferences TO authenticated;
ALTER POLICY "Users can view own contracts" ON public.contracts TO authenticated;
ALTER POLICY "Users can insert own contracts" ON public.contracts TO authenticated;
ALTER POLICY "Users can delete own contracts" ON public.contracts TO authenticated;
ALTER POLICY "Users can view own invoices" ON public.invoices TO authenticated;
ALTER POLICY "Users can insert own invoices" ON public.invoices TO authenticated;
ALTER POLICY "Users can delete own invoices" ON public.invoices TO authenticated;
ALTER POLICY "Users can view own billable hours" ON public.billable_hours TO authenticated;
ALTER POLICY "Users can insert own billable hours" ON public.billable_hours TO authenticated;
ALTER POLICY "Users can delete own billable hours" ON public.billable_hours TO authenticated;
ALTER POLICY "Users can view own conflict checks" ON public.conflict_checks TO authenticated;
ALTER POLICY "Users can insert own conflict checks" ON public.conflict_checks TO authenticated;
ALTER POLICY "Users can view own documents" ON public.documents TO authenticated;
ALTER POLICY "Users can insert own documents" ON public.documents TO authenticated;
ALTER POLICY "Users can delete own documents" ON public.documents TO authenticated;
ALTER POLICY "Users can view own events" ON public.calendar_events TO authenticated;
ALTER POLICY "Users can insert own events" ON public.calendar_events TO authenticated;
ALTER POLICY "Users can delete own events" ON public.calendar_events TO authenticated;
ALTER POLICY "Users can view own drafts" ON public.saved_drafts TO authenticated;
ALTER POLICY "Users can insert own drafts" ON public.saved_drafts TO authenticated;
ALTER POLICY "Users can delete own drafts" ON public.saved_drafts TO authenticated;
ALTER POLICY "Users can view own activity" ON public.activity_log TO authenticated;
ALTER POLICY "Users can insert own activity" ON public.activity_log TO authenticated;
ALTER POLICY "Admins can view all activity" ON public.activity_log TO authenticated;
REVOKE EXECUTE ON FUNCTION public.has_role(uuid, app_role) FROM anon, public;